/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
import { Product } from "./utils/model/product.interface";
import { ShoppingCartItem } from "./utils/model/shoppingcart.interface";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface StencilCart {
    }
    interface StencilFooter {
    }
    interface StencilHeader {
    }
    interface StencilLoadingItem {
    }
    interface StencilProductDetail {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface StencilProductListing {
        "category": number;
        "match"?: MatchResults;
    }
    interface StencilProductListingEnty {
        "history": RouterHistory;
        "match"?: MatchResults;
        "product": Product;
    }
    interface StencilShop {
    }
    interface StencilShopCartEntry {
        "shoppingCartEntry": ShoppingCartItem;
    }
    interface StencilShopIndex {
    }
    interface StencilShoppingCart {
    }
    interface StencilShoppingCartHeader {
        "items": ShoppingCartItem[];
    }
    interface ViewCart {
    }
    interface ViewProductDetail {
        "match": MatchResults;
    }
    interface ViewShop {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLStencilCartElement extends Components.StencilCart, HTMLStencilElement {
    }
    var HTMLStencilCartElement: {
        prototype: HTMLStencilCartElement;
        new (): HTMLStencilCartElement;
    };
    interface HTMLStencilFooterElement extends Components.StencilFooter, HTMLStencilElement {
    }
    var HTMLStencilFooterElement: {
        prototype: HTMLStencilFooterElement;
        new (): HTMLStencilFooterElement;
    };
    interface HTMLStencilHeaderElement extends Components.StencilHeader, HTMLStencilElement {
    }
    var HTMLStencilHeaderElement: {
        prototype: HTMLStencilHeaderElement;
        new (): HTMLStencilHeaderElement;
    };
    interface HTMLStencilLoadingItemElement extends Components.StencilLoadingItem, HTMLStencilElement {
    }
    var HTMLStencilLoadingItemElement: {
        prototype: HTMLStencilLoadingItemElement;
        new (): HTMLStencilLoadingItemElement;
    };
    interface HTMLStencilProductDetailElement extends Components.StencilProductDetail, HTMLStencilElement {
    }
    var HTMLStencilProductDetailElement: {
        prototype: HTMLStencilProductDetailElement;
        new (): HTMLStencilProductDetailElement;
    };
    interface HTMLStencilProductListingElement extends Components.StencilProductListing, HTMLStencilElement {
    }
    var HTMLStencilProductListingElement: {
        prototype: HTMLStencilProductListingElement;
        new (): HTMLStencilProductListingElement;
    };
    interface HTMLStencilProductListingEntyElement extends Components.StencilProductListingEnty, HTMLStencilElement {
    }
    var HTMLStencilProductListingEntyElement: {
        prototype: HTMLStencilProductListingEntyElement;
        new (): HTMLStencilProductListingEntyElement;
    };
    interface HTMLStencilShopElement extends Components.StencilShop, HTMLStencilElement {
    }
    var HTMLStencilShopElement: {
        prototype: HTMLStencilShopElement;
        new (): HTMLStencilShopElement;
    };
    interface HTMLStencilShopCartEntryElement extends Components.StencilShopCartEntry, HTMLStencilElement {
    }
    var HTMLStencilShopCartEntryElement: {
        prototype: HTMLStencilShopCartEntryElement;
        new (): HTMLStencilShopCartEntryElement;
    };
    interface HTMLStencilShopIndexElement extends Components.StencilShopIndex, HTMLStencilElement {
    }
    var HTMLStencilShopIndexElement: {
        prototype: HTMLStencilShopIndexElement;
        new (): HTMLStencilShopIndexElement;
    };
    interface HTMLStencilShoppingCartElement extends Components.StencilShoppingCart, HTMLStencilElement {
    }
    var HTMLStencilShoppingCartElement: {
        prototype: HTMLStencilShoppingCartElement;
        new (): HTMLStencilShoppingCartElement;
    };
    interface HTMLStencilShoppingCartHeaderElement extends Components.StencilShoppingCartHeader, HTMLStencilElement {
    }
    var HTMLStencilShoppingCartHeaderElement: {
        prototype: HTMLStencilShoppingCartHeaderElement;
        new (): HTMLStencilShoppingCartHeaderElement;
    };
    interface HTMLViewCartElement extends Components.ViewCart, HTMLStencilElement {
    }
    var HTMLViewCartElement: {
        prototype: HTMLViewCartElement;
        new (): HTMLViewCartElement;
    };
    interface HTMLViewProductDetailElement extends Components.ViewProductDetail, HTMLStencilElement {
    }
    var HTMLViewProductDetailElement: {
        prototype: HTMLViewProductDetailElement;
        new (): HTMLViewProductDetailElement;
    };
    interface HTMLViewShopElement extends Components.ViewShop, HTMLStencilElement {
    }
    var HTMLViewShopElement: {
        prototype: HTMLViewShopElement;
        new (): HTMLViewShopElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "stencil-cart": HTMLStencilCartElement;
        "stencil-footer": HTMLStencilFooterElement;
        "stencil-header": HTMLStencilHeaderElement;
        "stencil-loading-item": HTMLStencilLoadingItemElement;
        "stencil-product-detail": HTMLStencilProductDetailElement;
        "stencil-product-listing": HTMLStencilProductListingElement;
        "stencil-product-listing-enty": HTMLStencilProductListingEntyElement;
        "stencil-shop": HTMLStencilShopElement;
        "stencil-shop-cart-entry": HTMLStencilShopCartEntryElement;
        "stencil-shop-index": HTMLStencilShopIndexElement;
        "stencil-shopping-cart": HTMLStencilShoppingCartElement;
        "stencil-shopping-cart-header": HTMLStencilShoppingCartHeaderElement;
        "view-cart": HTMLViewCartElement;
        "view-product-detail": HTMLViewProductDetailElement;
        "view-shop": HTMLViewShopElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface StencilCart {
    }
    interface StencilFooter {
    }
    interface StencilHeader {
    }
    interface StencilLoadingItem {
    }
    interface StencilProductDetail {
        "history"?: RouterHistory;
        "match": MatchResults;
    }
    interface StencilProductListing {
        "category"?: number;
        "match"?: MatchResults;
    }
    interface StencilProductListingEnty {
        "history"?: RouterHistory;
        "match"?: MatchResults;
        "product"?: Product;
    }
    interface StencilShop {
    }
    interface StencilShopCartEntry {
        "shoppingCartEntry"?: ShoppingCartItem;
    }
    interface StencilShopIndex {
    }
    interface StencilShoppingCart {
    }
    interface StencilShoppingCartHeader {
        "items"?: ShoppingCartItem[];
    }
    interface ViewCart {
    }
    interface ViewProductDetail {
        "match"?: MatchResults;
    }
    interface ViewShop {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "stencil-cart": StencilCart;
        "stencil-footer": StencilFooter;
        "stencil-header": StencilHeader;
        "stencil-loading-item": StencilLoadingItem;
        "stencil-product-detail": StencilProductDetail;
        "stencil-product-listing": StencilProductListing;
        "stencil-product-listing-enty": StencilProductListingEnty;
        "stencil-shop": StencilShop;
        "stencil-shop-cart-entry": StencilShopCartEntry;
        "stencil-shop-index": StencilShopIndex;
        "stencil-shopping-cart": StencilShoppingCart;
        "stencil-shopping-cart-header": StencilShoppingCartHeader;
        "view-cart": ViewCart;
        "view-product-detail": ViewProductDetail;
        "view-shop": ViewShop;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "stencil-cart": LocalJSX.StencilCart & JSXBase.HTMLAttributes<HTMLStencilCartElement>;
            "stencil-footer": LocalJSX.StencilFooter & JSXBase.HTMLAttributes<HTMLStencilFooterElement>;
            "stencil-header": LocalJSX.StencilHeader & JSXBase.HTMLAttributes<HTMLStencilHeaderElement>;
            "stencil-loading-item": LocalJSX.StencilLoadingItem & JSXBase.HTMLAttributes<HTMLStencilLoadingItemElement>;
            "stencil-product-detail": LocalJSX.StencilProductDetail & JSXBase.HTMLAttributes<HTMLStencilProductDetailElement>;
            "stencil-product-listing": LocalJSX.StencilProductListing & JSXBase.HTMLAttributes<HTMLStencilProductListingElement>;
            "stencil-product-listing-enty": LocalJSX.StencilProductListingEnty & JSXBase.HTMLAttributes<HTMLStencilProductListingEntyElement>;
            "stencil-shop": LocalJSX.StencilShop & JSXBase.HTMLAttributes<HTMLStencilShopElement>;
            "stencil-shop-cart-entry": LocalJSX.StencilShopCartEntry & JSXBase.HTMLAttributes<HTMLStencilShopCartEntryElement>;
            "stencil-shop-index": LocalJSX.StencilShopIndex & JSXBase.HTMLAttributes<HTMLStencilShopIndexElement>;
            "stencil-shopping-cart": LocalJSX.StencilShoppingCart & JSXBase.HTMLAttributes<HTMLStencilShoppingCartElement>;
            "stencil-shopping-cart-header": LocalJSX.StencilShoppingCartHeader & JSXBase.HTMLAttributes<HTMLStencilShoppingCartHeaderElement>;
            "view-cart": LocalJSX.ViewCart & JSXBase.HTMLAttributes<HTMLViewCartElement>;
            "view-product-detail": LocalJSX.ViewProductDetail & JSXBase.HTMLAttributes<HTMLViewProductDetailElement>;
            "view-shop": LocalJSX.ViewShop & JSXBase.HTMLAttributes<HTMLViewShopElement>;
        }
    }
}
